- name: "### --- Playbook to create a rootCA with openssl --- ###"
  hosts: 127.0.0.1
  gather_facts: no
  vars:
      
  tasks:
    - name: "Create SSL-Server-Certificate"
      include_role:
        name: rootca-with-openssl
        tasks_from: create-server-certificate.yaml
      vars:
        dir: "./example-CA/"
        # This is the root-folder of your rootCA and some necessary needed folders
        dir_rootca: "{{ dir }}rootca/"
        dir_rootca_database: "{{ dir_rootca }}database/"
        dir_rootca_private: "{{ dir_rootca }}private/"
        dir_rootca_serial: "{{ dir_rootca }}serial/"
        dir_rootca_cnf: "{{ dir_rootca }}cnf/"
        # This is the folder, where your ssl-server-certificates will be placed. Please have a look inside for new created ssl-certificates
        dir_new_ssl_certs: "{{dir}}new-created-ssl-certs/"

        # This is the name and ip-adress of the system to which the ssl-certificate will be applied
        dnsname: "test-server"
        server_ip: "192.168.0.1"
        # Here you can define the FQDN of the Root-CA
        organization:
          # server: "/C=DE/ST=Hessen/L=Wiesbasen/OU=KBS/CN=serverLA"
          server: "/CN={{dnsname}}/ST=Niedersachsen/C=DE/L=Wilhelmshaven/E=patrick.jahn@sva.de/O=BW/OU=Marine"

        # Here you can define the length of your rootCA-certificate and server-cert angeben
        days:
          server_crt: "1825" # 5 years for the server-certificate

        # Name of the Server Cert, Key und CSR
        ssl_server_key_name: "{{dnsname}}.key"
        ssl_server_csr_name: "{{dnsname}}.csr"
        ssl_server_crt_name: "{{dnsname}}.crt"
        ssl_server_passphrase_for_private_key: "Test1234"

        # Alternative DNS-Names
        ## for the Server
        server_dns_alt_names:
          dns1: "{{dnsname}}"
          dns2: "{{server_ip}}"
          dns3: "*.artifactory.home.local"
