### PLEASE be careful with this. It removes the folder of your PKI
- name: "Prüfe, ob 'are_you_sure' auf true gesetzt ist"
  ansible.builtin.fail:
    msg: >
      Das Playbook wird abgebrochen, da 'are_you_sure' nicht auf true gesetzt ist.
      Bitte führe das Playbook mit 'are_you_sure: true' aus, um fortzufahren.
  when: not (are_you_sure | default(false) | bool)

- name: "Überprüfe, ob der Ordner existiert"
  ansible.builtin.stat:
    path: "{{ dir | default('my-root-ca') }}"
  register: rootca_status

- name: "Erstelle Backup-Verzeichnis (falls nicht vorhanden)"
  ansible.builtin.file:
    path: "backup"
    state: directory
  when: rootca_status.stat.exists

- name: "Setze den Backup-Zielpfad inklusive Datum und Uhrzeit"
  ansible.builtin.set_fact:
    backup_dest: "backup/{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  when: rootca_status.stat.exists

- name: "Verschiebe den Ordner {{ dir | default('my-root-ca') }} in das Backup-Verzeichnis"
  ansible.builtin.shell: "mv -T '{{ dir | default('my-root-ca') }}' '{{ backup_dest }}'"
  when: rootca_status.stat.exists
