- name: "### --- Playbook to create a rootCA with openssl --- ###"
  hosts: pi
  become_user: pi
  gather_facts: false

# Beginn TASKs
  tasks:
    # - import_role:
    #     name: rootca-with-openssl

# Create prerequisites of the RootCA
    - name: Run setup of rootCA-Folder-Structure
      ansible.builtin.import_role:
        name: rootca-with-openssl
        tasks_from: create-rootca-prereqs.yaml

# Create the RootCA private-Key, csr and crt
    - name: Run Creation of rootCA
      ansible.builtin.import_role:
        name: rootca-with-openssl
        tasks_from: create-rootca.yaml

# Create the server-Certifikat for serverLA
    - name: Run Creation of server-certificate
      ansible.builtin.import_role:
        name: rootca-with-openssl
        tasks_from: create-server-certificate.yaml
