---
# Erstellen des private-key
# - name: "Private Key für Server-Zertifikat erstellen"
#   raw: "/usr/bin/openssl genpkey -algorithm RSA -out {{ dir_new_ssl_certs }}{{ ssl_server_key_name }} -aes256"

# Erstellen des csr
# - name: "SSL-Zertifikats-Request (CSR) für Server-Zertifikat erstellen"
#   raw: "/usr/bin/openssl req -x509 -new -key {{ dir_new_ssl_certs }}{{ssl_server_key_name}} -out {{ dir_new_ssl_certs }}{{server_cert.ssl_server_csr_name}} -days 3650 -subj \"/C=DE/ST=Hessen/L=Wiesbasen/OU=KBS/CN=serverLA\""

- name: "SSL-Zertifikats-Request (CSR) für Server-Zertifikat erstellen"
  raw: "/usr/bin/openssl req -newkey rsa:2048 -keyout {{ dir_new_ssl_certs }}{{ssl_server_key_name}} -out {{ dir_new_ssl_certs }}{{ssl_server_csr_name}} -days {{ days.server_crt }} -passout pass:{{ssl_server_passphrase_for_private_key}} -subj \"{{distinguished_name.server}}\" -reqexts SAN -config <(cat {{dir_rootca_cnf}}openssl.cnf <(printf \"\n[SAN]\nsubjectAltName=DNS.1:{{server_dns_alt_names_dns1}},DNS.2:{{server_dns_alt_names_dns2}}\"))"

# CSR von RootCA signieren (Zertifikat ausstellen)
- name: "SSL-Zertifikats-Request (CSR) signieren und SSL-Zertifikat ausstellen"
  raw: "openssl x509 -req -in {{ dir_new_ssl_certs }}{{ssl_server_csr_name}} -passin pass:{{rootca_server_passphrase_for_private_key}} -CA {{ dir_rootca }}{{rootca_server_crt_name}} -CAkey {{ dir_rootca }}{{rootca_server_key_name}} -CAcreateserial -out {{ dir_new_ssl_certs }}{{ssl_server_crt_name}} -days {{ days.server_crt }} -extensions server_cert -extfile <(printf \"[server_cert]\nbasicConstraints = CA:FALSE\nkeyUsage = digitalSignature, keyEncipherment\nextendedKeyUsage = serverAuth\nsubjectAltName = @alt_names\n[ alt_names ]\n DNS.1={{server_dns_alt_names_dns1}}\nDNS.2={{server_dns_alt_names_dns2}}\nDNS.3={{server_dns_alt_names_dns3}}\")"

