- name: "### --- Playbook to create a rootCA with openssl --- ###"
  hosts: 127.0.0.1
  gather_facts: no
      
# Beginn TASKs
  tasks:
    # - import_role:
    #     name: rootca-with-openssl

# Create prerequisites of the RootCA
    - name: Run setup of rootCA-Folder-Structure
      import_role:
        name: rootca-with-openssl
        tasks_from: create-rootca-prereqs.yaml

# Create the RootCA private-Key, csr and crt
    - name: Run Creation of rootCA
      import_role:
        name: rootca-with-openssl
        tasks_from: create-rootca.yaml

# Create the server-Certifikat for serverLA
    - name: Run Creation of server-certificate
      import_role:
        name: rootca-with-openssl
        tasks_from: create-server-certificate.yaml
